modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="darksouls"
version="0.1.0"
displayName="Minecraft: Dark Souls"
displayURL="NONE"
logoFile="logo.png"
credits="My THICC brain and Forge"
authors="Skullman Games"
description=''' 
Welcome to the bonfire, Undead One. This first version of the Dark Souls Mod contains Bonfires, Fire Keepers, Estus Flasks and a first thread in form of Hollows.
'''
