modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Skullman-G/MC-Dark-Souls/issues"

[[mods]]
modId="darksouls"
version="0.4.0"
displayName="Minecraft: Dark Souls"
updateJSONURL="https://raw.githubusercontent.com/Skullman-G/MC-Dark-Souls/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-dark-souls"
logoFile="logo.png"
credits="My THICC brain and Forge"
authors="Skullman Games"
description=''' 
Adds concepts and features from From Software's "Dark Souls" trilogy.
'''