modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="darksouls"
version="0.1.4"
displayName="Minecraft: Dark Souls"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-dark-souls"
logoFile="logo.png"
credits="My THICC brain and Forge"
authors="Skullman Games"
description=''' 
Adds concepts and features from From Software's "Dark Souls" trilogy.
'''
