package com.skullmangames.darksouls.common.animation;

public enum LivingMotion
{
	NONE, IDLE, ANGRY, FLOATING, BENDING, WALKING, RUNNING, SWIMMING, FLYING, SNEAKING, KNEELING,
	FALL, MOUNTED, CHASING, SPELLCASTING, JUMPING, CELEBRATE, ADMIRE,
	AIMING, RELOADING, SHOOTING, THROW_JAVELIN, EATING, DRINKING, CONSUME_SOUL,
	POSING, DIGGING, INACTION, BLOCKING;
}